[default]
workshop = [
    "450814997",  # CBA_A3's Workshop ID
    "463939057",  # ACE3
#    "2369477168", # Advanced Developer Tools
    "1779063631", # ZEN
]

dlc = [
]

optionals = [
]

parameters = [
    "-window",
    "-noPause",
    "-noPauseAudio",
]

# executable = "arma3_x64"        # Default: "arma3_x64"
# file_patching = true # Default: true
# binarize = false # Default: false
# rapify = true # Default: true

[test]
extends = "default"
mission = "test.VR"


[vn]
extends = "test"
dlc = ["vn"]

[spe]
extends = "test"
dlc = ["vn", "spe"]

[asp]
extends = "test"
workshop = [
    "1645973522", # Intercept Minimal Dev
    "1652506957", # Arma Script Profiler
]